name: Test Python 3

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install -y ghostscript
  
      - name: Fix ImageMagick GhostScript permissions
        run: |
          sudo sed -i 's/domain="coder" rights="none"/domain="coder" rights="read\|write"/' /etc/ImageMagick-6/policy.xml


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools twine wheel coveralls
          pip install -e .[tests]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
            pycodestyle plotextractor && pytest tests
